version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
    ports:
      - 3000:80

  node-app:
    build: .
    env_file: ./.env
    # ports:
    #   - 3000:3000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:5.0.11

  redis:
    image: redis:7.0