version: '3'
services:
  nginx:
    depends_on:
      - node-app
    ports:
      - 3000:80

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=rofung
      - MONGO_PASSWORD=A12345678
      - SESSION_SECRET=c041c19e-8d1c-49bf-adcb-0f9650c6d4cf
    # ports:
    #   - 3000:3000
    command: node node-app/index.js

  mongo:
    volumes:
      - mongo-db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rofung
      - MONGO_INITDB_ROOT_PASSWORD=A12345678

volumes:
  mongo-db: